### ISSUE TITLE
Implementar colores como opciones de widget

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ludica-squamata/azoemapeditor#1]
```
En la r34 (hace mucho), habías comentado que la idea era implementar los 
colores (como mínimo) desde un json/script. Te parece que llegó el momento de 
hacer eso? Es un detalle estético, pero por ejemplo, en mi netbook, no sé 
porqué no tengo todos los colores (el filedialog no se ve bien, por ejemplo).

```

Original issue reported on code.google.com by `danielro...@gmail.com` on 20 Feb 2015 at 3:19

**Comment by zenieldanaku** [comment]
Los colores personalizados ya están implementados desde el commit https://github.com/ludica-squamata/azoemapeditor/commit/490dc368966285263f359325dbbad6acc0cce4d9. Si bien para cambiarlos hay que editar el archivo config.json (de momento, manualmente), ese archivo tiene más que ver con el issue #6 Preferencias que con este.
